# Generated by Django 4.0.3 on 2022-03-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='second.phone_number'),
        ),
    ]
